import type { Employment } from "@/lib";

export const employment_0: Employment = {
  company: "GovernmentCIO / GovCIO",
  role: "Senior Developer",
  industry: "Federal Government (DHS)",
  date: "03/2021 - 05/2025",
  text: "Led front-end development team in creating internal tools for the Department of Homeland Security. Designed applications, overseeing full lifecycle from application blueprinting and Figma design files to front-end architecture, development, and implementation. Served as Lead Front-End Developer and mentored junior developers to uphold coding and design standards. Engaged actively in Agile methodology to enhance development efficiency. This was a remote role that required Colin Birdwell to use equipment furnished by the government to stay within federal security protocols.",
  skills: [
    "React",
    "Typescript",
    "Javascript",
    "HTML",
    "CSS",
    "Redux",
    "Redux Toolkit",
    "Github",
    "Figma",
    "Axure",
    "VSCode",
    "Jira",
    "NodeJS",
    "Axios",
    "RTK Query",
    "ServiceNow",
    "Visual Studio Code",
  ],
};

export const employment_1: Employment = {
  company: "Small Dog Agency",
  role: "Freelance Developer & Designer",
  industry: "Digital Marketing",
  date: "10/2017 - 04/2020",
  text: "This role involved delivering subcontracted designs or coding assignments under NDA with quick turnaround times. This could range from creating design mockups, wireframes, and editing to development projects involving creation of single page sites, supporting already existing sites, email templates, and creating micro service applications with React JS. The grand majority of work was done remotely with occasional face to face meetings with the clients.",
  skills: [
    "React",
    "Typescript",
    "Javascript",
    "HTML",
    "CSS",
    "SaSS",
    "Redux",
    "Github",
    "Figma",
    "VSCode",
    "Jira",
    "NodeJS",
    "Axios",
    "Wordpress",
    "ModX",
    "Shopify",
    "Axios",
  ],
};

export const employment_2: Employment = {
  company: "Payment Data Systems / USIO",
  role: "Frontend Developer",
  industry: "Financial Technology",
  date: "04/2018 - 07/2019",
  text: "Was the sole front-end developer, responsible for coordinating with designers, back-end engineers, and stakeholders. Duties included creating email templates, updating features on the company website, and rebuilding the companies’ proprietary debit card app Akimbo in React-Native. This role was on-site in San Antonio, TX.",
  skills: [
    "React-Native",
    "React",
    "Xcode",
    "Redux",
    "HTML",
    "CSS",
    "GitHub",
    "Javascript",
    "Axios",
    "VSCode",
    "Sketch",
    "Plaid",
  ],
};

export const employment_3: Employment = {
  company: "Sistema Technologies",
  role: "Frontend Developer",
  industry: "Local Government (San Antonio Water System)",
  date: "01/2017 - 02/2018",
  text: "Spearheaded maintenance and feature development for San Antonio Water System's online platforms during contract with largest drinking water and sewage utility in Bexar County. Led efforts in converting websites to modern content management systems, while ensuring seamless integration and functionality. This position was on-site in San Antonio, TX.",
  skills: [
    "React",
    "JQuery",
    "Javascript",
    "HTML",
    "CSS",
    "GitHub",
    "SaSS",
    "Gulp",
    "Visual Studio Code",
    "Microsoft Visual Studio",
    "Sublime Text",
    "Jira",
    "NodeJS",
    "Axios",
    "Ajax",
    "Wordpress",
    "ModX",
  ],
};

export const employment_4: Employment = {
  company: "Signet Interactive",
  role: "Junior Developer",
  industry: "Digital Marketing",
  date: "01/2014 - 06/2016",
  text: "Crafted and launched boutique and single-page micro websites tailored for promotional initiatives. Converted desktop websites to fully mobile responsive, ensuring seamless user experiences across devices. Developed email templates and signatures to support comprehensive digital marketing strategies. This position was on-site in Houston, TX.",
  skills: [
    "JQuery",
    "Javascript",
    "HTML",
    "CSS",
    "GitHub",
    "Gulp",
    "Sublime",
    "Axios",
    "Wordpress",
    "Shopify",
    "Joomla",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "ModX",
  ],
};

export const employmentData: Employment[] = [
  employment_0,
  employment_1,
  employment_2,
  employment_3,
  employment_4,
];
